### ISSUE TITLE
Format parameter doesn't work

### ISSUE THREAD

**Issue by neonwired** [RandomAPI/Randomuser.me-old-source#51]
http://api.randomuser.me/?format=csv still returns a json result

**Comment by devdrops** [comment]
Also http://api.randomuser.me/?format=sql. The only format that works is YAML.

**Comment by mbifulco** [comment]
:+1: agreed, in particular I was looking for CSV to work, in my case.

**Comment by keitharm** [comment]
The CSV/XML/SQL format features will make a return in the node.js version of the generator.

For now, please use version 0.6: http://api.randomuser.me/0.6/?format=csv

**Comment by mbifulco** [comment]
Ah great, thanks @keitharm!

**Comment by keitharm** [comment]
Hi @mbifulco, just wanted to let you know that the Node.js version of the Random User Generator has been released and includes the CSV format option :)

**Comment by mbifulco** [comment]
Excellent, thanks @keitharm :+1: :100:
